"""
Django settings for Pure_Beurre project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import Pure_Beurre.the_secrets as tst
import os, platform
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

# Sentry configurations
sentry_sdk.init(
    dsn="https://e676a5c6788848648c538b327734b0c6@o520694.ingest.sentry.io/5631401",
    integrations=[DjangoIntegration()],
    traces_sample_rate=1.0,

    # If you wish to associate users to errors (assuming you are using
    # django.contrib.auth) you may enable sending PII data.
    send_default_pii=True
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = tst.SECRET_KEY
GMAP_KEY = tst.GMAP_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if DEBUG:
    ALLOWED_HOSTS = ["127.0.0.1"]
else:
    ALLOWED_HOSTS = ["206.189.30.229"]


# Application definition

INSTALLED_APPS = [
    'django_crontab',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dbbackup',
    'substitute',
]

# Backup DataBase Configurations
DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': BASE_DIR / 'backup/'}

# Cyclic tasks Configurations
# 00 */2 * * * => At every 2nd hour
# 0 3 * * 0 => At 03:00 every Sunday
# */2 * * * * => Every two minutes
# */10 * * * * => Every ten minutes
CRONJOBS = [
    ('0 3 * * 0', 'django.core.management.call_command', ['updateDB']),
    ('*/10 * * * *', 'django.core.management.call_command', ['updateDB']),
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Pure_Beurre.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Pure_Beurre.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'purebeurre_db',
            'USER': 'stephen',
            'PASSWORD': 'stephen',
            'HOST': '127.0.0.1',
            'PORT': '5432',
        }
    }
else:
    if 'travis' in platform.uname().node:
        # This database configuration is used by Travis
        DATABASES = {
            'default': {
                # 'ENGINE': 'django.db.backends.postgresql',
                'ENGINE': 'django.db.backends.postgresql_psycopg2',
                'NAME': 'purebeurre',
                'USER': 'postgres',
                'PASSWORD': '',
                'HOST': '',
                'PORT': '',
            },
        }
    elif platform.uname().node == 'django-s-1vcpu-1gb-lon1-01':
        # This database configuration is used by Digital Ocean
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql_psycopg2',
                'NAME': 'purebeurre',
                'USER': 'purebeurre',
                'PASSWORD': 'purebeurreoc',
                'HOST': 'localhost',
                'PORT': '',
            }
        }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [("substitute/static"),]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


DATA_UPLOAD_MAX_NUMBER_FIELDS = 20000

if DEBUG:
    # SMTP dev Configuration
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = "devdjangotest@gmail.com"
    EMAIL_HOST_PASSWORD = "devdjangotest.1234"

else:
    if 'travis' in platform.uname().node:
        # SMTP Test Configuration
        EMAIL_BACKEND = ""
        EMAIL_HOST = ""
        EMAIL_PORT = 587
        EMAIL_USE_TLS = True
        EMAIL_HOST_USER = ""
        EMAIL_HOST_PASSWORD = ""

    elif platform.uname().node == 'django-s-1vcpu-1gb-lon1-01':
        # SMTP prod Configuration
        EMAIL_BACKEND = ""
        EMAIL_HOST = ""
        EMAIL_PORT = 587
        EMAIL_USE_TLS = True
        EMAIL_HOST_USER = ""
        EMAIL_HOST_PASSWORD = ""

